---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-form
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-form
  template:
    metadata:
      labels:
        app: angular-form
    spec:
      containers:
      - name: angular-form
        image: shubhamsk512/angular-form:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
